name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Check Python Version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build_and_check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check if any file has changed in the last 5 minutes
        id: check_changes
        run: |
          git fetch origin main
          COMMIT_COUNT=$(git log origin/main --since="5 minutes ago" --pretty=format:"%H" | wc -l)
          if [ $COMMIT_COUNT -gt 0 ]; then
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "has_changes=false" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        if: env.has_changes == 'true'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          ALPINE_DIGEST=$(curl -s https://hub.docker.com/v2/repositories/library/python/tags/alpine | jq -r '.images[0].digest')
          STABLE_VERSION=$(curl -s https://hub.docker.com/v2/repositories/library/python/tags/?page_size=100 | \
            jq -r --arg ALPINE_DIGEST "$ALPINE_DIGEST" \
            '.results[] | select(.images[0].digest == $ALPINE_DIGEST) | .name' | \
            grep -E '^[0-9]+(\.[0-9]+){0,2}-alpine$' | sort -V | tail -n 1 | sed 's/-alpine$//')
          
          echo "VERSION=${STABLE_VERSION}" >> $GITHUB_ENV
          docker build -t erstt/rap:python${{ env.VERSION }} -t erstt/rap:latest .
          docker push erstt/rap:python${{ env.VERSION }}
          docker push erstt/rap:latest
