name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Check Python Version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build_and_check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the time of the last commit
        id: get_commit_time
        run: |

          LAST_COMMIT_TIME=$(git log -1 --format=%ct)
          echo "LAST_COMMIT_TIME=${LAST_COMMIT_TIME}" >> $GITHUB_ENV

      - name: Check if recent changes exist
        id: check_recent_changes
        run: |

          CURRENT_TIME=$(date +%s)

          TIME_DIFF=$((CURRENT_TIME - LAST_COMMIT_TIME))


          THRESHOLD=300

          if [ $TIME_DIFF -lt $THRESHOLD ]; then
            echo "has_recent_changes=true" >> $GITHUB_ENV
          else
            echo "has_recent_changes=false" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        if: env.has_recent_changes == 'true'
        run: |
          VERSION=$(xmllint --xpath 'string(//latest)' version/python.xml)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
          docker build -t erstt/rap:python${{ env.VERSION }} -t erstt/rap:latest .
          docker push erstt/rap:python${{ env.VERSION }}
          docker push erstt/rap:latest
